env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - eslint:recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  react/jsx-filename-extension: [0, { "extensions": [".js", ".jsx"] }],
  react/prop-types: 0,
  react/function-component-definition: 0,
  react-hooks/exhaustive-deps: 0,
  import/no-unresolved: 0,
  import/extensions: 0,
  no-console: 0
}
